
$env:LLM_PROVIDER="groq"
$env:GROQ_API_KEY="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"
$env:GROQ_MODEL="llama-3.1-8b-instant"
$env:POSTGRES_HOST="localhost"
$env:POSTGRES_PORT="5432"
$env:POSTGRES_DB="si_vectors"
$env:POSTGRES_USER="si_user"
$env:POSTGRES_PASSWORD="si_password"
$env:VECTOR_BACKEND="pgvector"
$env:REDIS_HOST="localhost"
$env:REDIS_PORT="6379"
$env:EMBEDDING_HOST="localhost"
$env:EMBEDDING_PORT="8080"
$env:MTLS_ENABLED="false"
$env:SI_ENV="development"
$env:SI_SECRET_KEY="change-me-in-production-use-openssl-rand-hex-32"
$env:KAFKA_BOOTSTRAP_SERVERS="localhost:9092"
$env:FALKORDB_HOST="localhost"
$env:FALKORDB_PORT="6380"
$env:SLA_P50_MS="150"
$env:SLA_P95_MS="500"
$env:SLA_P99_MS="1500"
$env:SLA_AVAILABILITY_PCT="99.5"
$env:SLA_RTO_MINUTES="30"
$env:SLA_RPO_MINUTES="5"
$env:OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"
$env:OTEL_SERVICE_NAME="solar-intelligence"
$env:VLLM_ROUTER_HOST="localhost"
$env:VLLM_ROUTER_PORT="8100"

Write-Host "Starting SI API on http://localhost:8888" -ForegroundColor Cyan
python -m uvicorn photosphere.api.main:app --host 0.0.0.0 --port 8888 --reload
